// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/_middleware.ts";
import * as $1 from "./routes/index.tsx";
import * as $2 from "./routes/login/_middleware.ts";
import * as $3 from "./routes/login/github/callback.ts";
import * as $4 from "./routes/login/github/index.ts";
import * as $5 from "./routes/login/index.tsx";
import * as $6 from "./routes/my/_middleware.ts";
import * as $7 from "./routes/my/index.tsx";
import * as $$0 from "./islands/AddEntry.tsx";
import * as $$1 from "./islands/EntryDelete.tsx";

const manifest = {
  routes: {
    "./routes/_middleware.ts": $0,
    "./routes/index.tsx": $1,
    "./routes/login/_middleware.ts": $2,
    "./routes/login/github/callback.ts": $3,
    "./routes/login/github/index.ts": $4,
    "./routes/login/index.tsx": $5,
    "./routes/my/_middleware.ts": $6,
    "./routes/my/index.tsx": $7,
  },
  islands: {
    "./islands/AddEntry.tsx": $$0,
    "./islands/EntryDelete.tsx": $$1,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
